services:
  - type: web
    name: django-backend
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: daphne -b 0.0.0.0 -p 10000 cropalert.asgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: cropalert.settings
